# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raspi_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raspi_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13raspi_message.proto\"\x17\n\x07NDarray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty\"\x14\n\x05Shape\x12\x0b\n\x03\x64im\x18\x01 \x03(\x05\"O\n\x0bInitRequest\x12\"\n\x12observation_shapes\x18\x01 \x03(\x0b\x32\x06.Shape\x12\x1c\n\x0c\x61\x63tion_shape\x18\x02 \x01(\x0b\x32\x06.Shape\"5\n\x13ObservationsRequest\x12\x1e\n\x0cobservations\x18\x01 \x03(\x0b\x32\x08.NDarray\"*\n\x0e\x41\x63tionResponse\x12\x18\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x08.NDarray2`\n\x0cRaspiMessage\x12\x1c\n\x04Init\x12\x0c.InitRequest\x1a\x06.Empty\x12\x32\n\tGetAction\x12\x14.ObservationsRequest\x1a\x0f.ActionResponseb\x06proto3'
)




_NDARRAY = _descriptor.Descriptor(
  name='NDarray',
  full_name='NDarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='NDarray.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=46,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=55,
)


_SHAPE = _descriptor.Descriptor(
  name='Shape',
  full_name='Shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='Shape.dim', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=77,
)


_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation_shapes', full_name='InitRequest.observation_shapes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_shape', full_name='InitRequest.action_shape', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=158,
)


_OBSERVATIONSREQUEST = _descriptor.Descriptor(
  name='ObservationsRequest',
  full_name='ObservationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='observations', full_name='ObservationsRequest.observations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=213,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='ActionResponse',
  full_name='ActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ActionResponse.action', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=257,
)

_INITREQUEST.fields_by_name['observation_shapes'].message_type = _SHAPE
_INITREQUEST.fields_by_name['action_shape'].message_type = _SHAPE
_OBSERVATIONSREQUEST.fields_by_name['observations'].message_type = _NDARRAY
_ACTIONRESPONSE.fields_by_name['action'].message_type = _NDARRAY
DESCRIPTOR.message_types_by_name['NDarray'] = _NDARRAY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Shape'] = _SHAPE
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['ObservationsRequest'] = _OBSERVATIONSREQUEST
DESCRIPTOR.message_types_by_name['ActionResponse'] = _ACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NDarray = _reflection.GeneratedProtocolMessageType('NDarray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:NDarray)
  })
_sym_db.RegisterMessage(NDarray)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Shape = _reflection.GeneratedProtocolMessageType('Shape', (_message.Message,), {
  'DESCRIPTOR' : _SHAPE,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:Shape)
  })
_sym_db.RegisterMessage(Shape)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

ObservationsRequest = _reflection.GeneratedProtocolMessageType('ObservationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONSREQUEST,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:ObservationsRequest)
  })
_sym_db.RegisterMessage(ObservationsRequest)

ActionResponse = _reflection.GeneratedProtocolMessageType('ActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONRESPONSE,
  '__module__' : 'raspi_message_pb2'
  # @@protoc_insertion_point(class_scope:ActionResponse)
  })
_sym_db.RegisterMessage(ActionResponse)



_RASPIMESSAGE = _descriptor.ServiceDescriptor(
  name='RaspiMessage',
  full_name='RaspiMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=259,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='RaspiMessage.Init',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAction',
    full_name='RaspiMessage.GetAction',
    index=1,
    containing_service=None,
    input_type=_OBSERVATIONSREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RASPIMESSAGE)

DESCRIPTOR.services_by_name['RaspiMessage'] = _RASPIMESSAGE

# @@protoc_insertion_point(module_scope)
